### ISSUE TITLE
License conflict

### ISSUE THREAD

**Issue by lluisp** [insideout10/stanbol-freeling#8]
Hi
   I found your stanbol integration of FreeLing and I think it is a great job.

   However, FreeLing 3.1 has a GPL license.
   Your wrapper is a derived work that links to the library, and thus it should be distributed under GPL.

   Distributing your wrapper under Apache license is violating GPL terms.  
  Please fix that as soon as possible.

```
Thank you very much

   Lluis Padro
```

**Comment by ziodave** [comment]
Thanks @lluisp we'll do it soon!
